global:
  scrape_interval: 30s

rule_files:
  - 'solana-rules.yml'

scrape_configs:
  - job_name: 'solana-exporter'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          app: 'solana'
          hostname: 'my-host.name'