{
 "title": "Protocol Stats Dashboard",
 "tags": [
  "solana",
  "blockchain"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "label": "Solana Network", "query": "mainnet" },
   {
    "name": "nodekey",
    "label": "Node Key",
    "query": {
     "query": "label_values(solana_validator_active_stake,nodekey)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "solana_validator_active_stake", "legendFormat": "__auto" },
    {
     "expr": "solana_validator_skip_percentage",
     "legendFormat": "__auto"
    },
    { "expr": "solana_validator_commission", "legendFormat": "__auto" },
    { "legendFormat": "__auto" },
    { "legendFormat": "__auto" },
    { "expr": "solana_validator_delinquent", "legendFormat": "__auto" }
   ]
  },
  { "title": "Global Stats & Aggregations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "stat",
   "description": "Aggregated amount of $SOL on Identity Account for selected Validators",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(solana_account_balance)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Epoch ",
   "type": "stat",
   "description": "This panel displays the current epoch number for the Solana **${network}** blockchain.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Epoch Ends",
   "type": "stat",
   "description": "This panel displays the estimated time remaining in the current epoch on the **${network}** network. \n",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{}}" }
   ]
  },
  {
   "title": "% Total Deliquency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_network_delinquent_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$SOL Price",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(solana_validator_active_stake)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Epoch% Progression",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, solana_network_epoch_elapsed_percentage)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Global TPS - ${network} ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    { "legendFormat": "Global TPS" }
   ]
  },
  { "title": "Validator Metrics - ${nodekey}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "hostname" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_delinquent{nodekey='$nodekey'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": " SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_account_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (nodekey) (solana_validator_active_stake{nodekey='$nodekey'})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vote Performance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_validator_vote_performance_percentage{nodekey='$nodekey'}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Staking ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solana_validator_active_stake{nodekey='$nodekey'}",
     "legendFormat": "Remote"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_version", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_last_vote{nodekey='$nodekey'}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{}}" }
   ]
  },
  {
   "title": "Skiprate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_skip_percentage{nodekey='$nodekey'}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_is_healthy", "legendFormat": " " }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solana_node_num_slots_behind", "legendFormat": "{{host}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_first_available_block",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_minimum_ledger_slot",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Slots rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "targets": [
    { "legendFormat": "Remote" }
   ]
  },
  {
   "title": "Vote credits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "legendFormat": "{{host}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (nodekey) (solana_validator_commission{nodekey='$nodekey'})",
     "legendFormat": "Validator Fees"
    }
   ]
  },
  {
   "title": "Leaderslots this Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_root_slot{nodekey='$nodekey'}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Skip rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (nodekey) (solana_validator_skip_percentage{nodekey='$nodekey'})",
     "legendFormat": "Validator Skip rate"
    },
    { "expr": "solana_network_skip_percentage", "legendFormat": "Cluster Skip rate" }
   ]
  },
  {
   "title": "Skip Delta",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_skip_delta{nodekey='$nodekey'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Newer Versions Percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_newer_versions_percentage{nodekey='$nodekey'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slots diff (pod - chain)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "legendFormat": "Slots Diff." }
   ]
  }
 ]
}